#!/usr/bin/env python3
# -*- coding: utf-8 -*- 

import getopt
import alsaaudio
import sys
import time
import matplotlib.pyplot as plt
import struct
import numpy
#import scipy.signal
from threading import Thread
from PIL import Image
import time
import peakutils

numpy.seterr(divide='ignore')

globalfftdatas = []
globalpeaks = []
audiodatas = []
counterbuffer=0

def usage():
	print('usage: recordtest.py [-i <lenght of data array to analyse> ] [-d <device>] [-p <plot mode>] [-r <rate>] [-o <output path for image plot>]', file=sys.stderr)
	print("example: ./NCWDECODER -d plughw:lp20,1  -r 384000 -p fftonly")
	print("example: ./NCWDECODER -d plughw:lp20,1-r 384000 -i 1000 -p tobmppeak -o ./playbook0/")
	print("plot can be 'fftonly' to see fft, 'watterfall' to see watterfall, 'tobmp' to registrer watterfall in hight resolution png")
	print("peak_threshold in %, peak_min_dist in hz")
	sys.exit(2)

class ThGetAudio(Thread):

	def __init__(self, audiodevice, RATE, chunksize):
		Thread.__init__(self)
		FORMAT = alsaaudio.PCM_FORMAT_S16_LE #use the most standard format for chunks values
		CHANNELS = 2 #in i/q system
		self.inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL , channels=CHANNELS, rate=RATE, format=FORMAT, periodsize=chunksize, device=audiodevice)	#init the audio input
		
	def audioinput(self): #read chunks and return à complex array for I/Q
		l, ret = self.inp.read()
		if l > 0:
			# datas=numpy.frombuffer(ret, numpy.int16)#unstruck the bytes in a array
			# return [complex(a,b) for a, b in zip(datas[::2],datas[1::2])] #transforme the int byt array of I real in left and  Q imgaginary right channel in complex 
			return numpy.frombuffer(ret, numpy.int16)#unstruck the bytes in a array
		else:
			print("overrun")
			
	def run(self):
		global audiodatas
		while True:
			audiodatas.append(self.audioinput())

class ThSpectrumAnalyzer(Thread):
	
	def __init__(self,datalenght):
		Thread.__init__(self)
		global globalpeaks, globalfftdatas, audiodatas
		self.datalenght=datalenght
		while not len(audiodatas):
			print("wait for audio chunk for start")
			time.sleep(0.1)
		print("audio data ready!")
		self.chunksize = len(audiodatas[0])
		self.window=[]
		for a in numpy.hanning(chunksize): #calculation of the hanning window and stored in a double array to facilitate multiplication
			self.window.append(a)
			self.window.append(a)
		print("hanning windows is compute: "+str(len(self.window))+"samples")
		
		self.windowbordermin=int(self.chunksize*20/100) #calculation of the fft min index data to be taken into account for the average speed during peak detection. For not to take into account the edges of the fft
		self.windowbordermax=int(self.chunksize-self.windowbordermin) #calculation of the fft max index data to be taken into account for the average speed during peak detection
		self.peakscore=[0]*int(self.chunksize/2)

	def fft(self, data1,data2,number=2):
		lendata=int(len(data1)/number)
		datas=[]
		arrayoffft=[]
		for i in range(number):
			datas = numpy.concatenate([data1[(i*lendata):], data2[:(i*lendata)]])
			# datas = data1[(i*lendata):] + data2[:(i*lendata)]
			datas = datas *self.window
			datasend = [complex(a,b) for a, b in zip(datas[::2],datas[1::2])]
			fd_spectrum_rot = numpy.fft.fftshift(numpy.fft.fft(datasend,norm="ortho"))
			arrayoffft.append(20.*numpy.log10(numpy.real(fd_spectrum_rot * fd_spectrum_rot.conj())))
		return arrayoffft

	def findpeakinfft(self, datas, thresoldv=1, min_distance=1): #
		#noisefloor = numpy.median(datas[self.windowbordermin:self.windowbordermax])+3 #calcul of the noise floor withut the borders and add 3db
		#print(minvalue)
		# peaks, _ = scipy.signal.find_peaks(datas, height=noisefloor,distance=min_distance,threshold=thresoldv,prominence=1,width=5)#compute peak searching with datas, height to the minimum value, distance minimal beetween two peaks, use threshold for not detect the same peak nearby
		peaks = peakutils.indexes(datas, thres=0.3, min_dist=5)
		return peaks
		
	def CWdetect(self, newpeaks):
		global globalpeaks
		for a in newpeaks:
			self.peakscore[a] = self.peakscore[a] + 5
		for i, val in enumerate(self.peakscore):
			self.peakscore[i] = self.peakscore[i] - 1
			if(val<0):
				self.peakscore[i]=0
				globalpeaks[i]=0
			elif (val > 50):
				globalpeaks[i]=1
			elif (val < 10):
				globalpeaks[i]=0
				
	def run(self):
		global globalpeaks, globalfftdatas, audiodatas, counterbuffer
		while True :
			# try:
			if len(audiodatas)>4:
				if len(audiodatas[0])>0 and len(audiodatas[1])>0:
					fftdatas = self.fft(audiodatas[0],audiodatas[1])
					for row in fftdatas:
						globalfftdatas.append(row)
						counterbuffer += 1
					while len(globalfftdatas) > self.datalenght:
						globalfftdatas.pop(0)
					if fftdatas:
						peaksindex = self.findpeakinfft(fftdatas[0])
						self.CWdetect(peaksindex)
					audiodatas.pop(0)
			else:
				time.sleep(0.1)
			# except:
				# pass
				# time.sleep(0.1)
				
class Thplot(Thread):

	def __init__(self, plot,outputdirectory,datalenght):
		Thread.__init__(self)
		self.datalenght = datalenght
		while(len(globalfftdatas)<10):
			time.sleep(0.2)
			
		if plot == "tobmp":
			self.arrimg=numpy.zeros((self.datalenght,len(globalfftdatas[0])), dtype=float)
		
		if plot == "tobmp" or plot == "watterfall":
			while(len(globalfftdatas)<self.datalenght):
				print("bufferisation:"+str(int(len(globalfftdatas)*100/self.datalenght))+"%")
				time.sleep(0.2)
				
		if plot == "fftonly":
			self.ylimax = numpy.amax(globalfftdatas[len(globalfftdatas)-1])
		
		
		self.outputdirectory = outputdirectory
		print("ready to plot:" + str(plot))

	def column(self,matrix, i):
		return [row[i-4:i+4] for row in matrix]

	def run(self):
		global globalpeaks, globalfftdatas, counterbuffer
		while True:
			if plot == "fftonly" and len(globalfftdatas):
				plt.ylim(0, self.ylimax)
				plt.plot(globalfftdatas[len(globalfftdatas)-1])
				plt.plot(globalpeaks)
				plt.draw()
				plt.pause(0.5)
				plt.clf()
			elif plot == "watterfall":
				while counterbuffer < self.datalenght:
					print("bufferisation:"+str(int(counterbuffer*100/self.datalenght))+"%")
					time.sleep(0.2)
				plt.ylim(0, len(globalfftdatas))
				plt.imshow(globalfftdatas[:self.datalenght]) 
				plt.draw()
				plt.pause(1)
				plt.clf()
				counterbuffer=0
			elif plot == "tobmp":
				while counterbuffer < self.datalenght:
						print("bufferisation:"+str(int(counterbuffer*100/self.datalenght))+"%")
						time.sleep(0.2)
				print("print image")
				numpy.copyto(self.arrimg, globalfftdatas[:self.datalenght])
				Image.fromarray(self.arrimg).convert("RGB").save(str(self.outputdirectory)+str(time.time())+'_out.png',optimize=False,quality=100)
				counterbuffer=0
				time.sleep(1)
			elif plot == "tobmppeak":
				imagecounter = 0
				while counterbuffer < self.datalenght:
						print("bufferisation:"+str(int(counterbuffer*100/self.datalenght))+"%")
						time.sleep(0.2)
				for i, val in enumerate(globalpeaks):
					if(val==1):
						imagecounter = imagecounter + 1
						self.arrimg = numpy.asarray(self.column(globalfftdatas[:self.datalenght],i))
						Image.fromarray(self.arrimg).convert("RGB").save(str(self.outputdirectory)+str(time.time())+str(i)+'_out.png',optimize=False,quality=100)
				counterbuffer=0
				print("find "+str(imagecounter)+" images")
				time.sleep(1)
	
if __name__ == "__main__":
	outputdirectory = "./"
	device = 'default'
	rate = 48000
	plot = False
	datalenght=1000
	peak_threshold=0.5
	peak_min_dist=5
	
	try:
		opts, args = getopt.getopt(sys.argv[1:], "i:o:p:hd:r:", ["--inputdatalenght=","--outputdirectory=","plot=","help", "device=", "rate=", "peak_threshold=", "peak_min_dist="])
	except getopt.GetoptError as err:
		print(err)
		usage()
		sys.exit(2)
	
	if len(opts)==0 :
		usage()
	
	for o, a in opts:
		if o in ("-h", "--help"):
			usage()
			sys.exit()
		elif o in ("-p", "--plot"):
			plot = a
		elif o in ("-d", "--device"):
			device = a
		elif o in ("-o", "--outputdirectory"):
			outputdirectory = a
		elif o in ("-r", "--rate"):
			rate = int(a)
		elif o in ("-i", "--datalenght"):
			datalenght = int(a)
		elif o in ("--peak_threshold"):
			peak_threshold = int(a/100)
		elif o in ("--peak_min_dist"):
			peak_min_dist = int(a/23) # fixed in the code 23hz bandwith
		else:
			assert False, "unhandled option"
			
	chunksize = int(rate * 2048 / 48000) #to get all time 23hz bandwith by pixel
	globalpeaks=[0]*chunksize
	
	print("device:" + device + "\nrate:" + str(rate) + "sample/s\npixel bandwith:"+"{:.1f}".format(rate/chunksize)+"hz/pix\ntime line resolution:"+str((chunksize/rate)*1000)+"ms")
	
	threadAudio = ThGetAudio(device,rate,chunksize)
	threadAudio.start()
	
	threadFFT = ThSpectrumAnalyzer(datalenght)
	threadFFT.start()
	
	if plot:
		if outputdirectory[len(outputdirectory)-1] != "/":
			outputdirectory = outputdirectory + "/"
		threadPlot = Thplot(plot,outputdirectory,datalenght)
		threadPlot.start()

	  	

